name: Build and release
on: push
jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true
    - name: Pin imgui submodule to v1.92.6
      shell: bash
      run: |
        cd app/dependencies/imgui
        git fetch --tags origin
        git checkout v1.92.6
    - name: Build debug executable
      run: |
        cmake . -G "Visual Studio 17 2022" -A Win32 -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE="Debug"
        cmake --build . -- /p:Configuration=Release
        mv app\Release\maniac.exe maniac-dbg.exe
    - name: Build release executable
      run: |
        cmake . -G "Visual Studio 17 2022" -A Win32 -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE="Release"
        cmake --build . -- /p:Configuration=Release
        mv app\Release\maniac.exe maniac-prd.exe
    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: maniac-prd
        path: maniac-prd.exe
    - name: Upload debug build
      uses: actions/upload-artifact@v4
      with:
        name: maniac-dbg
        path: maniac-dbg.exe
  release:
    name: Create release and upload builds
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download release build
      uses: actions/download-artifact@v4
      with:
        name: maniac-prd
    - name: Download debug build
      uses: actions/download-artifact@v4
      with:
        name: maniac-dbg
    - name: Create release and upload assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          maniac-prd.exe
          maniac-dbg.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
